### ISSUE TITLE
DateInput component should support minDate, maxDate, and excludedDates properties

### ISSUE THREAD

**Issue by yurigenin** [zippytech/react-toolkit#1]
Currently, there is no way to restrict input to a particular range of dates. Very often in business applications there is a need to set a maxDate or a minDate to restrict user input. Another useful feature is providing a set of dates to be excluded/disabled so that user cannot select them.

**Comment by zpytchrb** [comment]
Thanks for bringing this up!

We do have https://docs.zippytech.io/calendar/api#props-isDisabledDay  which is the most powerful way of disabling certain dates. Additionally, we do have https://docs.zippytech.io/calendar/api#props-minDate and https://docs.zippytech.io/calendar/api#props-maxDate 

Below you can find an example of configuring the `Calendar` component used in a `DateInput` - nest the calendar inside the dateinput and configure it with the desired props
```jsx
import React from 'react'
import DateInput from '@zippytech/react-toolkit/DateInput'
import '@zippytech/react-toolkit/Calendar/index.css'
import Calendar from '@zippytech/react-toolkit/Calendar'

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = { date: null }
  }

  render() {
    return <div>
      <code>dateFormat='DD-MM-YYYY': {this.state.date}</code><br />
      <DateInput
          dateFormat="DD-MM-YYYY"
          date={this.state.date}
          onChange={date => this.setState({ date })}
        >
           <Calendar isDisabledDay={() => true}/>
       </DateInput>
    </div>
  }
}

export default () => <App />
```

If you only want `minDate` and `maxDate`, they are already available on the `DateInput`

```jsx
      <DateInput
        dateFormat="DD-MM-YYYY"
        maxDate="23-05-2018"
      />
```

I will add this to our official docs, so everyone can benefit. Let us know how it goes.

**Comment by zpytchrb** [comment]
We've updated the docs - see https://docs.zippytech.io/dateinput#configuring-the-calendar-component and https://docs.zippytech.io/dateinput#disabled-dates-min-&-max-dates
