### ISSUE TITLE
ProgressBar tickStyle is not used correctly

### ISSUE THREAD

**Issue by yurigenin** [zippytech/react-toolkit#4]
When Ticks are being rendered the **style** property is being used instead of the **ticksStyle** for the ticks container element. **ticksStyle** property is not used at all. So when I pass **tickStyle.backgroundColor** to paint tick marks in a different color it is instead passed to the **style** property and results in painting the entire progress bar in that color.

```
return (
      <Ticks
        style={tickStyle}
        ticksStyle={ticksStyle}
        tickStyle={tickStyle}
        renderTick={renderTick}
        className={className}
        tickClassName={tickClassName}
        formatedTick={formatedTick}
        directionMap={directionMap}
        stepTickDirection={stepTickDirection}
        value={value}
      />
    );
```

**Comment by zpytchrb** [comment]
Should be fixed in `1.0.63`
